version: '3.1'

services:

  db:
    image: postgres:12.17-alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
      POSTGRES_DB: dbname
    ports:
      - 5353:5432 
    volumes:
      - ./prisma/db_volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8998:8080